[tool]

[tool.poetry]
name = "jupysnips"
version = "1.0.0"
description = "Jupyter snippets for Python 3"
authors = ["David Dahan <david.dahan3@gmail.com>"]

[tool.poetry.dependencies]
python = "3.11.5"
ipdb = "*"        # https://github.com/gotcha/ipdb
ipykernel = "*"   # https://github.com/ipython/ipykernel

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
